import { db } from './database';
import type { Category, Product, Customer, StoreSettings, CashShift } from '../types';

export const DEFAULT_SETTINGS: StoreSettings = {
  id: 'default-settings',
  storeName: 'QuickMart Superstore',
  storeNameBn: 'কুইকমার্ট সুপারস্টোর',
  branchName: 'Dhanmondi Branch',
  tagline: 'Fresh Quality & Best Value',
  address: 'House #42, Road #9/A, Dhanmondi, Dhaka-1209',
  phone: '+880 1712-345678',
  email: 'info@quickmartpos.com',
  vatRegistrationNumber: 'BIN-002938491-0101',
  currencySymbol: '৳',
  currencyCode: 'BDT',
  defaultTaxRate: 5,
  enableTax: true,
  paperSize: '80mm',
  receiptHeaderNote: 'Thank you for shopping with us!',
  receiptFooterNote: 'Goods once sold can be exchanged within 3 days with original receipt.',
  enableSound: true,
  autoPrintReceipt: true,
  cashierName: 'Tanvir Ahmed',
};

export const SEED_CATEGORIES: Category[] = [
  { id: 'cat-all', name: 'All Products', nameBn: 'সকল পণ্য', iconName: 'LayoutGrid', order: 0 },
  { id: 'cat-grocery', name: 'Grocery & Staples', nameBn: 'মুদি ও চাল-ডাল', iconName: 'ShoppingBag', color: 'emerald', order: 1 },
  { id: 'cat-beverages', name: 'Beverages & Drinks', nameBn: 'পানীয় ও জুস', iconName: 'Coffee', color: 'amber', order: 2 },
  { id: 'cat-bakery', name: 'Bakery & Snacks', nameBn: 'বেকারি ও স্ন্যাকস', iconName: 'Cookie', color: 'orange', order: 3 },
  { id: 'cat-dairy', name: 'Dairy & Eggs', nameBn: 'দুধ ও ডিম', iconName: 'Milk', color: 'blue', order: 4 },
  { id: 'cat-personal', name: 'Personal Care', nameBn: 'ব্যক্তিগত যত্ন', iconName: 'Sparkles', color: 'purple', order: 5 },
  { id: 'cat-fruits', name: 'Fresh Fruits', nameBn: 'তাজা ফলমূল', iconName: 'Apple', color: 'rose', order: 6 },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    sku: 'BEV-COC-500',
    barcode: '89411001001',
    name: 'Coca Cola 500ml',
    nameBn: 'কোকা কোলা ৫০০ মি.লি.',
    categoryId: 'cat-beverages',
    costPrice: 38,
    salePrice: 45,
    stock: 64,
    minStockAlert: 10,
    unit: 'pcs',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=300&auto=format&fit=crop&q=60',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-002',
    sku: 'BEV-SPR-500',
    barcode: '89411001002',
    name: 'Sprite 500ml Pet Bottle',
    nameBn: 'স্প্রাইট ৫০০ মি.লি.',
    categoryId: 'cat-beverages',
    costPrice: 38,
    salePrice: 45,
    stock: 45,
    minStockAlert: 10,
    unit: 'pcs',
    imageUrl: 'https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=300&auto=format&fit=crop&q=60',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-003',
    sku: 'BEV-RED-250',
    barcode: '89411001003',
    name: 'Red Bull Energy Drink 250ml',
    nameBn: 'রেড বুল ২৫০ মি.লি.',
    categoryId: 'cat-beverages',
    costPrice: 170,
    salePrice: 210,
    stock: 22,
    minStockAlert: 5,
    unit: 'pcs',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=300&auto=format&fit=crop&q=60',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-004',
    sku: 'GRO-MIN-5KG',
    barcode: '89411002001',
    name: 'Miniket Premium Rice 5kg',
    nameBn: 'মিনিকেট প্রিমিয়াম চাল ৫ কেজি',
    categoryId: 'cat-grocery',
    costPrice: 380,
    salePrice: 420,
    stock: 35,
    minStockAlert: 8,
    unit: 'packet',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300&auto=format&fit=crop&q=60',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-005',
    sku: 'GRO-SOY-1LT',
    barcode: '89411002002',
    name: 'Rupchanda Fortified Soybean Oil 1L',
    nameBn: 'রূপচাঁদা সয়াবিন তেল ১ লিটার',
    categoryId: 'cat-grocery',
    costPrice: 172,
    salePrice: 190,
    stock: 50,
    minStockAlert: 12,
    unit: 'ltr',
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=300&auto=format&fit=crop&q=60',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-006',
    sku: 'GRO-SUG-1KG',
    barcode: '89411002003',
    name: 'Fresh Refined Sugar 1kg',
    nameBn: 'ফ্রেশ চিনি ১ কেজি',
    categoryId: 'cat-grocery',
    costPrice: 128,
    salePrice: 140,
    stock: 4,
    minStockAlert: 10,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1581441363689-1f3c3c414635?w=300&auto=format&fit=crop&q=60',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-007',
    sku: 'BAK-BRD-400',
    barcode: '89411003001',
    name: 'All Time Milk Bread 400g',
    nameBn: 'অল টাইম মিল্ক ব্রেড ৪০০ গ্রাম',
    categoryId: 'cat-bakery',
    costPrice: 52,
    salePrice: 65,
    stock: 18,
    minStockAlert: 5,
    unit: 'packet',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=300&auto=format&fit=crop&q=60',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-008',
    sku: 'BAK-ORE-120',
    barcode: '89411003002',
    name: 'Oreo Original Biscuit 120g',
    nameBn: 'ওরিও বিস্কুট ১২০ গ্রাম',
    categoryId: 'cat-bakery',
    costPrice: 45,
    salePrice: 60,
    stock: 80,
    minStockAlert: 15,
    unit: 'packet',
    imageUrl: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=300&auto=format&fit=crop&q=60',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-009',
    sku: 'DAI-MLK-1LT',
    barcode: '89411004001',
    name: 'Aarong Pasteurised Liquid Milk 1L',
    nameBn: 'আড়ং তরল দুধ ১ লিটার',
    categoryId: 'cat-dairy',
    costPrice: 82,
    salePrice: 95,
    stock: 25,
    minStockAlert: 8,
    unit: 'ltr',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=300&auto=format&fit=crop&q=60',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-010',
    sku: 'DAI-EGG-12P',
    barcode: '89411004002',
    name: 'Farm Fresh Brown Eggs (12 pcs)',
    nameBn: 'ফার্মের লাল ডিম (১২ টি)',
    categoryId: 'cat-dairy',
    costPrice: 145,
    salePrice: 165,
    stock: 30,
    minStockAlert: 6,
    unit: 'box',
    imageUrl: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=300&auto=format&fit=crop&q=60',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-011',
    sku: 'PER-DOV-100',
    barcode: '89411005001',
    name: 'Dove Beauty Moisture Bar Soap 100g',
    nameBn: 'ডাভ বিউটি সোপ ১০০ গ্রাম',
    categoryId: 'cat-personal',
    costPrice: 95,
    salePrice: 120,
    stock: 42,
    minStockAlert: 10,
    unit: 'pcs',
    imageUrl: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=300&auto=format&fit=crop&q=60',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-012',
    sku: 'FRU-APP-1KG',
    barcode: '89411006001',
    name: 'Fuji Fresh Red Apples 1kg',
    nameBn: 'ফুজি লাল আপেল ১ কেজি',
    categoryId: 'cat-fruits',
    costPrice: 280,
    salePrice: 340,
    stock: 15,
    minStockAlert: 5,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=300&auto=format&fit=crop&q=60',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-013',
    sku: 'FRU-BAN-1DZ',
    barcode: '89411006002',
    name: 'Sagor Banana (1 Dozen)',
    nameBn: 'সাগর কলা (১ ডজন)',
    categoryId: 'cat-fruits',
    costPrice: 90,
    salePrice: 120,
    stock: 20,
    minStockAlert: 4,
    unit: 'box',
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=300&auto=format&fit=crop&q=60',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-014',
    sku: 'BEV-NES-200',
    barcode: '89411001004',
    name: 'Nescafe Classic Instant Coffee 200g',
    nameBn: 'নেসক্যাফে কফি ২০০ গ্রাম',
    categoryId: 'cat-beverages',
    costPrice: 650,
    salePrice: 780,
    stock: 12,
    minStockAlert: 3,
    unit: 'pcs',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=300&auto=format&fit=crop&q=60',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-015',
    sku: 'GRO-MAG-8PK',
    barcode: '89411002004',
    name: 'Maggi 2-Minute Masala Noodles (8-Pack)',
    nameBn: 'ম্যাগি মসলা নুডুলস (৮ প্যাক)',
    categoryId: 'cat-grocery',
    costPrice: 155,
    salePrice: 180,
    stock: 55,
    minStockAlert: 10,
    unit: 'packet',
    imageUrl: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=300&auto=format&fit=crop&q=60',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'cust-walkin',
    name: 'Walk-in Customer (নগদ খরিদ্দার)',
    phone: '00000000000',
    address: 'Counter Direct Sale',
    totalSpent: 0,
    totalOrders: 0,
    currentDue: 0,
    creditLimit: 0,
    loyaltyPoints: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cust-001',
    name: 'Rahimul Islam',
    phone: '01819234567',
    address: 'Flat 4B, Green Road, Dhaka',
    totalSpent: 12450,
    totalOrders: 8,
    currentDue: 850,
    creditLimit: 5000,
    loyaltyPoints: 120,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cust-002',
    name: 'Mahmuda Begum',
    phone: '01711987654',
    address: 'House #12, Road #5, Dhanmondi',
    totalSpent: 28900,
    totalOrders: 15,
    currentDue: 0,
    creditLimit: 10000,
    loyaltyPoints: 340,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cust-003',
    name: 'Kamal Hossain (Restaurant Owner)',
    phone: '01912445566',
    address: 'Food Corner, Zigatola',
    totalSpent: 64500,
    totalOrders: 22,
    currentDue: 3200,
    creditLimit: 20000,
    loyaltyPoints: 580,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

let initPromise: Promise<void> | null = null;

export async function initializeDatabase(): Promise<void> {
  if (initPromise) return initPromise;

  initPromise = (async () => {
    try {
      const existingCategories = await db.categories.count();
      if (existingCategories === 0) {
        await db.categories.bulkPut(SEED_CATEGORIES);
      }

      const existingProducts = await db.products.count();
      if (existingProducts === 0) {
        await db.products.bulkPut(SEED_PRODUCTS);
      }

      const existingCustomers = await db.customers.count();
      if (existingCustomers === 0) {
        await db.customers.bulkPut(SEED_CUSTOMERS);
      }

      const existingSettings = await db.settings.get('default-settings');
      if (!existingSettings) {
        await db.settings.put(DEFAULT_SETTINGS);
      }

      const existingShifts = await db.shifts.count();
      if (existingShifts === 0) {
        const initialShift: CashShift = {
          id: 'shift-' + Date.now(),
          cashierName: DEFAULT_SETTINGS.cashierName,
          openedAt: new Date().toISOString(),
          status: 'open',
          startingCash: 2000,
          cashSales: 0,
          cardSales: 0,
          bkashSales: 0,
          nagadSales: 0,
          dueSales: 0,
          totalSales: 0,
          totalOrders: 0,
          cashIn: 0,
          cashOut: 0,
          expectedCashInDrawer: 2000,
        };
        await db.shifts.put(initialShift);
      }
    } catch {
      // Fallback
    }
  })();

  return initPromise;
}

